### ISSUE TITLE
Add Gerber or Kicad?

### ISSUE THREAD

**Issue by Xav83130** [Hasenpups/WLED_ESP32_Controller#1]
Hello,
I think your card design is very good, congratulations;
Do you think it is possible to put on the Github, the Gerber or Kicad files?
I would like to add a fuse and especially adjust the components for a slightly different board. (my level in electronics is really low).
thank you in advance
Xavier

**Comment by Hasenpups** [comment]
Sorry this can not be done as the design is not open for personal use at the moment. 
I will add it later.

**Comment by Hasenpups** [comment]
> Hello, I think your card design is very good, congratulations; Do you think it is possible to put on the Github, the Gerber or Kicad files? I would like to add a fuse and especially adjust the components for a slightly different board. (my level in electronics is really low). thank you in advance Xavier

Gerber files are now online.
